### ISSUE TITLE
Guidance for rsas.solve outflow variable

### ISSUE THREAD

**Issue by dwilusz1** [charman2/rsas#9]
In release 0.5.3, I formatted the outflow variable for rsas.solve as [Q, ET] (i.e., "rsas.solve(J, [Q,ET], ...), which gave me the error: "Q must be a 1 or 2-D numpy array with a column for each outflow\nor a list of two 1-D numpy arrays (like ''[Q1, Q2]'')".  The error is confusing because it seems to be telling me to do the thing that produced the error.

I got it to work when I changed the outflow input to "np.array([Q, ET]).T"

Unless I'm mistaken, the fix here may be to clarify the documentation and change the error message.

**Comment by charman2** [comment]
This was an error in the input handling. It has been fixed in the latest commit.
